### PR TITLE
Handle private ECR image references containing public.ecr.aws

### LINKED ISSUE #651: Private ECR repository contains "public.ecr.aws" breaks the GetCredentials
**What happened**:

In our company, we intend to do image copy from public repository to our private ECR repository, just because we don't want to encounter network issue that may cause the image pulling to be slow/failed.

Currently our naming convention of the repository looks like: `$ecr_repository_url$public_repository_name:$image_tag.`

A concrete example would be, for image `public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12`, we'll do a replication as `112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12`

So as for kubelet's image pulling, we're facing `Failed getting credential from external registry credential provider: error execing credential provider plugin ecr-credential-provider for image 112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/public.ecr.aws/aws-observability/aws-for-fluent-bit: exit status 1`.

The above error results to image pulling failed with 401 Unauthorized issue.

After digging the source code, I've noticed that the `ecrPlugin.GetCredentials` uses a keyword `public.ecr.aws` to determine if the given image is a public repository or not.

Thus in our case, a credential request was falsely made to publilc registry instead of private registry.

Screen Shot 2023-09-04 at 20 19 27

**What you expected to happen**:

Even with the keyword `public.ecr.aws` present in the image url, the `ecr-credential-provider` shall still be able to determin if the image is in private registry or not.

**How to reproduce it (as minimally and precisely as possible)**:

Create a private repository and image with keyword `public.ecr.aws`, for example, `112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12`.

Then invoke directly the `ecr-credential-provider` with:

```
echo '{"kind":"CredentialProviderRequest","apiVersion":"credentialprovider.kubelet.k8s.io/v1","image":"112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/public.ecr.aws/aws-observability/aws-for-fluent-bit:2.31.12"}' | /etc/eks/image-credential-provider/ecr-credential-provider
I0904 12:24:55.935639   30684 main.go:95] Getting creds for public registry
E0904 12:24:57.143893   30684 main.go:261] Error running credential provider plugin: UnrecognizedClientException: The security token included in the request is invalid
	status code: 400, request id: 05cad298-32ce-4775-85b2-d23ce746f26e
```

For comparaision, use another repository and image, `112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/aws-observability/aws-for-fluent-bit:2.31.12`:

```
echo '{"kind":"CredentialProviderRequest","apiVersion":"credentialprovider.kubelet.k8s.io/v1","image":"112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/aws-observability/aws-for-fluent-bit:2.31.12"}' | /etc/eks/image-credential-provider/ecr-credential-provider
I0904 12:26:23.827086   31239 main.go:126] Getting creds for private registry 112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn/aws-observability/aws-for-fluent-bit:2.31.12
{"kind":"CredentialProviderResponse","apiVersion":"credentialprovider.kubelet.k8s.io/v1","cacheKeyType":"Registry","cacheDuration":"6h0m0s","auth":{"112233445566.dkr.ecr.cn-northwest-1.amazonaws.com.cn":{"username":"AWS","password":"REDACTED"}}}
```

**Anything else we need to know?**:

Nein.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.4-eks-2d98532", GitCommit:"3d90c097c72493c2f1a9dd641e4a22d24d15be68", GitTreeState:"clean", BuildDate:"2023-07-28T16:51:44Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
  ```
  NAME="Amazon Linux"
  VERSION="2"
  ID="amzn"
  ID_LIKE="centos rhel fedora"
  VERSION_ID="2"
  PRETTY_NAME="Amazon Linux 2"
  ANSI_COLOR="0;33"
  CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
  HOME_URL="https://amazonlinux.com/"
  ```
- Kernel (e.g. `uname -a`): `Linux ip-172-24-155-214.cn-northwest-1.compute.internal 5.10.186-179.751.amzn2.x86_64 #1 SMP Tue Aug 1 20:51:38 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by cartermckinnon**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When support was added for `public.ecr.aws` images, a simple `string.Contains` was used to determine whether a requested image reference was a private or public ECR repository. If you use `public.ecr.aws` anywhere in your image reference, such as:
```
123456789123.dkr.ecr.us-west-2.amazonaws.com/public.ecr.aws/foo:latest
```
Then public ECR creds will be retrieved, and image pulls will fail (or you'll fail to call `ecr-public::GetAuthorizationToken` if your IAM creds don't have permissions for it).

**Which issue(s) this PR fixes**:

Fixes #651

**Special notes for your reviewer**:

I did some cleanup while I was at it:
- I removed the `RegistryIds` parameter to `GetAuthorizationTokenInput`. This field is deprecated and has no effect on the token returned.

**Does this PR introduce a user-facing change?**:

```release-note
Fixes an issue with private ECR image references that contain `public.ecr.aws` being misidentified as public ECR repositories.
```

### CODE REVIEW

File: cmd/ecr-credential-provider/main.go [hunk 1]
```diff
@@ -162,10 +153,15 @@ func (e *ecrPlugin) GetCredentials(ctx context.Context, image string, args []str
 	var creds *credsData
 	var err error
 
-	if strings.Contains(image, ecrPublicURL) {
```
Comment (cartermckinnon) [inline cmd/ecr-credential-provider/main.go:165]: This is the bug.

**Review by mmerkes — COMMENTED** [review]
Overall, the change LGTM. What testing did you do on this? At a minimum, we should verify that this can pull a public and private image.

File: cmd/ecr-credential-provider/main.go [hunk 2]
```diff
@@ -116,43 +115,35 @@ func (e *ecrPlugin) getPublicCredsData() (*credsData, error) {
...
 		authToken: output.AuthorizationData.AuthorizationToken,
 		expiresAt: output.AuthorizationData.ExpiresAt,
 	}, nil
 }
 
-func (e *ecrPlugin) getPrivateCredsData(image string) (*credsData, error) {
-	klog.Infof("Getting creds for private registry %s", image)
-	registryID, region, registry, err := parseRepoURL(image)
+func (e *ecrPlugin) getPrivateCredsData(imageHost string, image string) (*credsData, error) {
+	var err error
```
Comment (tzneal) [inline cmd/ecr-credential-provider/main.go:124]:
```suggestion

```
Don't *think* this is needed.

Comment (cartermckinnon) [reply cmd/ecr-credential-provider/main.go]: Ah you're right, I added this prior to line 126. Thx

**Review by mmerkes — APPROVED** [review]
LGTM

**Comment by cartermckinnon** [comment]
/assign @nckturner 

can you give this a look Nick?

File: cmd/ecr-credential-provider/main.go [hunk 3]
```diff
@@ -219,24 +214,25 @@ func getCacheDuration(expiresAt *time.Time) *metav1.Duration {
...
+}
 
-	splitURL := ecrPattern.FindStringSubmatch(parsed.Hostname())
-	if len(splitURL) < 4 {
-		return "", "", "", fmt.Errorf("%s is not a valid ECR repository URL", parsed.Hostname())
+func parseRegionFromECRPrivateHost(host string) (string, error) {
+	splitHost := ecrPrivateHostPattern.FindStringSubmatch(host)
+	if len(splitHost) != 6 {
+		return "", fmt.Errorf("invalid private ECR host: %s", host)
 	}
```
Comment (jBouyoud) [inline cmd/ecr-credential-provider/main.go:234]: Hi, 

This is not really this purpose of this PR and probably should be done in another one. I put a comment here to open the discussion, If you think relevant don't hesitate to move this in a dedicated PR or issue.

I wonder if it's really needed to _generate an error here_ and not relying on SDK default region (and potential user configuration in provider configuration - `AWS_REGION` env var for exemple).

With something like (aka do not generate an error on this function): 
```suggestion
if len(splitHost) != 6 {
  return "", nil
}
```
(further code updates will be probably needed) 
this provider will rely on AWS SDK default, and let opportunity to users to handle more uses cases.

Especially, when users ( me ;-) ) want to configure containerd mirroring to ECS registry (with pull through cache feature)

I'll be glad to help on this topic, please let me known how.
Regards

--
My use case detail : 
- ECR Pull through cache to `public.ecr.aws` , `quay.io` and `registry.k8s.io`
- Containerd configured to mirror `public.ecr.aws` , `quay.io` and `registry.k8s.io` to my private registry
- Private registry is hosted on another account (cross account scenario)
- aws-ecr-credential-provider configured to generate credentials for : `public.ecr.aws` , `quay.io` and `registry.k8s.io` with a config file like : 
  ```json
  {
  "apiVersion": "kubelet.config.k8s.io/v1alpha1",
  "kind": "CredentialProviderConfig",
  "providers": [
    {
      "name": "ecr-credential-provider",
      "matchImages": [
        "*.dkr.ecr.*.amazonaws.com",
        "*.dkr.ecr.*.amazonaws.com/*",
        "*.dkr.ecr.*.amazonaws.com.cn",
        "*.dkr.ecr-fips.*.amazonaws.com",
        "*.dkr.ecr.*.c2s.ic.gov",
        "*.dkr.ecr.*.sc2s.sgov.gov",
        "quay.io",
        "public.ecr.aws",
        "registry.k8s.io"
      ],
      "defaultCacheDuration": "12h",
      "apiVersion": "credentialprovider.kubelet.k8s.io/v1alpha1"
    }
  ]
 }
  ```

Comment (cartermckinnon) [reply cmd/ecr-credential-provider/main.go:234]: Can you open a new issue? I understand the use case but removing this validation probably isn't the right solution.

**Review by tzneal — APPROVED** [review]
/lgtm

**Comment by cartermckinnon** [comment]
@dims PTAL?

**Comment by matty-rose** [comment]
hey @cartermckinnon we ran into this issue quite recently, super nice to see the fix merged in already 🎉  - do you have an idea on the cadence/ETA that the `ecr-credential-provider` with this fix will be incorporated into the EKS AMIs?
