### PR TITLE
Fix target group instances registration when TG created

### LINKED ISSUE #301: Target group has empty instances list after creation
**What happened**: When creating k8s service with **service.beta.kubernetes.io/aws-load-balancer-type: nlb** , we constantly get an empty list target group

**What you expected to happen**: instances are registered in the target group just as part of target group creation process

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod and service like
```---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nlb-sample-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
```

**Anything else we need to know?**:
Workaround: restart of aws-cloud-controller-manager daemonset, which triggers ensureLoadBalancerv2() function again and instances registration appears

**Environment**:
- Kubernetes version (use `kubectl version`): 
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"archive", BuildDate:"2021-09-23T18:53:32Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1+k0s", GitCommit:"b230d3e4b9d6bf4b731d96116a6643786e16ac3f", GitTreeState:"clean", BuildDate:"2021-12-24T12:59:32Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.11.0-1027-aws
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by abubyr**
In case of creating a new TG removed return dropped off  #this function
just before instance registration code. Daemon restart was needed to
call ensureTargetGroup() again and reach out registration code
(as targetGroup != nil, TG already created)

Change-Id: I57717602624d9632049596e6928ac4671387905d

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: fix of instances registration in AWS NLB target group during its creation

**Which issue(s) this PR fixes**:

Fixes #301

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/providers/v1/aws_loadbalancer.go [hunk 1]
```diff
@@ -618,8 +618,7 @@ func (c *Cloud) ensureTargetGroup(targetGroup *elbv2.TargetGroup, serviceName ty
 			return nil, fmt.Errorf("expected only one target group on CreateTargetGroup, got %d groups", len(result.TargetGroups))
 		}
 
-		tg := result.TargetGroups[0]
-		return tg, nil
+		targetGroup = result.TargetGroups[0]
```
Comment (jaypipes) [inline pkg/providers/v1/aws_loadbalancer.go:621]: Seems like a simple fix. I wonder, @nckturner or @M00nF1sh, maybe this was coded this way originally because we wanted to sleep some period of time after creation of a TargetGroup before attempting to register expected instances in the TargetGroup below on original line 632?

Comment (glebiller) [reply pkg/providers/v1/aws_loadbalancer.go:621]: I encountered the same issue with 1.23.0 today where the target group had no target registered.
Restarting the controller seems to have correctly updated the target group.

The return might be there to make a sleep, but I am not sure we are doing the reconcile loop again unless there is a change in the service.

I will try your version and see if it's happening again.

**Comment by glebiller** [comment]
I just tried this fix using a cluster that is created every morning for multiple days in a row. It's correctly populating the target groups when first deploying the cloud controller \o/.
With the latest released version, the cloud controller needs to be restarted in order to have the target groups filled.

**Review by olemarkus — APPROVED** [review]

**Comment by nullzone** [comment]
Hello,

This issue is still happening in 1.24.3 (causing a lot of issues and forcing us to move to CLB which the consequent reduction in the features like the possibility of assigning fixed IPs in the LBs).

Any idea when this merge could get accepted as part of a following release?

**Comment by olemarkus** [comment]
This PR has been released.

**Comment by mariusmarais** [comment]
@olemarkus There is no 1.24.1 in the Github Releases for this project, only 1.24.0 on 13 May. Is there another place to look for release info?

**Comment by olemarkus** [comment]
Try setting something like this 
```
spec:
  cloudControllerManager:
    image:   registry.k8s.io/provider-aws/cloud-controller-manager:v1.24.1
```

I'll see to this being bumped in kOps shortly.

**Comment by JoelSpeed** [comment]
I recently came across this and I think I've found the original issue, https://github.com/kubernetes/cloud-provider-aws/pull/293/files#diff-70a4ebdf516a65404dc3c3b3ba9925fc62d0f85bd75e272a4f8ddb4b7b8ab852L620-L623

These lines were dropped, I'm guessing unintentionally and meant that the chunking work also got broken. IMO we should be reverting this PR and reinstating these lines, the end of this block should be like below, as it was originally
```
		tg := result.TargetGroups[0]
		tgARN := aws.StringValue(tg.TargetGroupArn)
		if err := c.ensureTargetGroupTargets(tgARN, expectedTargets, nil); err != nil {
			return nil, err
		}
		return tg, nil
```
