### PR TITLE
fix/e2e/loadbalancer: preventing binding on privileged ports, and added nlb cases

### LINKED ISSUE #1150: e2e tests for 'loadbalancer' is failing in distributions which restricts privileged ports
**What happened**:

The e2e test `[cloud-provider-aws-e2e] loadbalancer [It] should configure the loadbalancer based on annotations` is failing when running in rootless container due the replicaSet/pod is scheduled to bind in privileged port, TCP/80. Some distributions by default runs rootless by default, leading to fail in the e2e test.

See the details:

```sh
Summarizing 1 Failure:
  [FAIL] [cloud-provider-aws-e2e] loadbalancer [It] should configure the loadbalancer based on annotations
 HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:83

Ran 1 of 5 Specs in 127.216 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 4 Skipped

$ kubectl -n cloud-provider-aws-2741 logs lbconfig-test-56c7n
I0526 19:28:02.597565       1 log.go:198] Started HTTP server on port 80
I0526 19:28:02.597815       1 log.go:198] listen tcp :80: bind: permission denied
```

**What you expected to happen**:

1. loadbalancer tests to pass in distributions with security restrictions

I see this test is expected to pass in the [Kubernetes CI][ccm-aws-ci-job], so I would like to ask:
- Can we update the test to fit more restrictive environments preventing the test pod to bind on privileged ports*? 

**How to reproduce it (as minimally and precisely as possible)**:

1. build e2e: `make test-e2e`
2. run loadbalancer tests focusing in loadbalancer
3. check the pod logs

```sh
./e2e.test  --ginkgo.focus="loadbalancer should configure the loadbalancer based on annotations"
[...]
  May 26 16:27:43.863: INFO: Pod "lbconfig-test-56c7n": Phase="Pending", Reason="", readiness=false. Elapsed: 150.294696ms
  May 26 16:27:43.863: INFO: Error evaluating pod condition running and ready: want pod 'lbconfig-test-56c7n' on 'ip-10-0-4-107.ec2.internal' to be 'Running' but was 'Pending'
  May 26 16:27:46.014: INFO: Pod "lbconfig-test-56c7n": Phase="Running", Reason="", readiness=false. Elapsed: 2.301704636s
  May 26 16:27:46.014: INFO: Error evaluating pod condition running and ready: pod 'lbconfig-test-56c7n' on 'ip-10-0-4-107.ec2.internal' didn't have condition {Ready True}; conditions: [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2025-05-26 16:27:44 -0300 -03  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2025-05-26 16:27:43 -0300 -03  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2025-05-26 16:27:43 -0300 -03 ContainersNotReady containers with unready status: [netexec]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2025-05-26 16:27:43 -0300 -03 ContainersNotReady containers with unready status: [netexec]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2025-05-26 16:27:43 -0300 -03  }]

[...]
  May 26 16:29:44.169: INFO: Unexpected error: 
      <*errors.errorString | 0xc0008180d0>: 
      failed waiting for pods to be running: timeout waiting for 1 pods to be ready
      {
          s: "failed waiting for pods to be running: timeout waiting for 1 pods to be ready",
      }
  May 26 16:29:44.169: FAIL: failed waiting for pods to be running: timeout waiting for 1 pods to be ready

  Full Stack Trace
  k8s.io/cloud-provider-aws/tests/e2e.init.func1.3()
  	HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:83 +0x1f7
  [FAILED] in [It] - HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:83 @ 05/26/25 16:29:44.169
  STEP: dump namespace information after failure @ 05/26/25 16:29:44.169
  [PANICKED] in [DeferCleanup (Each)] - HOME/src/go1.23.6.linux-amd64/src/runtime/panic.go:262 @ 05/26/25 16:29:44.169
  STEP: Destroying namespace "cloud-provider-aws-2741" for this suite. @ 05/26/25 16:29:44.169
• [FAILED] [127.215 seconds]
[cloud-provider-aws-e2e] loadbalancer [It] should configure the loadbalancer based on annotations
HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:46

  [FAILED] May 26 16:29:44.169: failed waiting for pods to be running: timeout waiting for 1 pods to be ready
  In [It] at: HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:83 @ 05/26/25 16:29:44.169

  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------
SSSS

Summarizing 1 Failure:
  [FAIL] [cloud-provider-aws-e2e] loadbalancer [It] should configure the loadbalancer based on annotations
 HOME/cloud-provider-aws/tests/e2e/loadbalancer.go:83

Ran 1 of 5 Specs in 127.216 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 4 Skipped

$ kubectl -n cloud-provider-aws-2741 logs lbconfig-test-56c7n
I0526 19:28:02.597565       1 log.go:198] Started HTTP server on port 80
I0526 19:28:02.597815       1 log.go:198] listen tcp :80: bind: permission denied
```

**Anything else we need to know?**:

*following the code I see this test is using the e2e framework[1] to deploy the pod, which looks like does not allow customization in the bind port of pods[2].

[ccm-aws-ci-job]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/cloud-provider-aws/1146/pull-cloud-provider-aws-e2e/1926018760578174976
[1] ccm-aws e2e loadbalancer test service spec: https://github.com/kubernetes/cloud-provider-aws/blob/42ef88f1517d6c6eecc078235b8dfa7cb1cabe07/tests/e2e/loadbalancer.go#L51-L80
[2] pod orchestration in the test framework: https://github.com/kubernetes/kubernetes/blob/4c2a741aacc6eea0ae1b0b345034434f9473f52b/test/e2e/framework/service/jig.go#L684

**Environment**:
- Kubernetes version (use `kubectl version`): (OpenShift distribution)
```
$ ./kubectl  version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.3
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by mtulio**
**What type of PR is this?**

/kind bug
/kind failing-test
/kind flake

**What this PR does / why we need it**:

This change fixes the e2e loadbalancer by preventing running tests in privileged ports, which was making tests to fail in distributions which restricts that configuration.

The issue details https://github.com/kubernetes/cloud-provider-aws/issues/1150 

Furthermore, this also introduce the test cases more generically, including two scenarios not covered yet:
- NLB 
- NLB with node selectors

**Which issue(s) this PR fixes**:

Fixes #1150

**Special notes for your reviewer**:

The test framework implements mostly the code, but unfortunately the port of the target/pod is tied to the library (jig) - not exported, causing some code duplication to provide one off fix here.

There is a discussion [here](https://github.com/kubernetes/cloud-provider-aws/issues/1150#issuecomment-2910617374) with some options.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mtulio** [comment]
~~~
$ ./e2e.test  --ginkgo.focus="loadbalancer" 
  W0530 00:08:35.130637 2533371 test_context.go:478] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
  May 30 00:08:35.130: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
Running Suite: AWS Cloud Provider End-to-End Tests - /devel/rosa
==============================================================================================
Random Seed: 1748574515 - will randomize all specs

Will run 3 of 5 specs
------------------------------
[cloud-provider-aws-e2e] loadbalancer should configure the loadbalancer based on annotations
(...)
• [134.221 seconds]
------------------------------
S
------------------------------
[cloud-provider-aws-e2e] loadbalancer NLB should configure the loadbalancer with target-node-labels
(....)
 May 30 00:11:16.617: INFO: Found 2 worker nodes
(...)

• [188.525 seconds]
------------------------------
S
------------------------------
[cloud-provider-aws-e2e] loadbalancer NLB should configure the loadbalancer based on annotations
(...)
• [178.780 seconds]
------------------------------

Ran 3 of 5 Specs in 501.527 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

~~~

**Comment by mtulio** [comment]
> @mtulio: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-cloud-provider-aws-e2e	[fdc9e65](https://github.com/kubernetes/cloud-provider-aws/commit/fdc9e65c79f421b54e52f9997bd63a254b877bc6)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/cloud-provider-aws/1153/pull-cloud-provider-aws-e2e/1928319600886288384)	true	`/test pull-cloud-provider-aws-e2e`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=cloud-provider-aws&pr=1153). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Amtulio). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/cloud-provider-aws/issues?q=is:issue+is:open) when you hit one in your PR.

oops, missed local changes. retesting:

/test pull-cloud-provider-aws-e2e

**Comment by mtulio** [comment]
> /test pull-cloud-provider-aws-e2e

/test pull-cloud-provider-aws-e2e

**Comment by mtulio** [comment]
> @mtulio: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-cloud-provider-aws-e2e	[9dc6148](https://github.com/kubernetes/cloud-provider-aws/commit/9dc6148042d0988ad83998bb477801396f4db683)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/cloud-provider-aws/1153/pull-cloud-provider-aws-e2e/1928597503163240448)	unknown	`/test pull-cloud-provider-aws-e2e`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=cloud-provider-aws&pr=1153). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Amtulio). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/cloud-provider-aws/issues?q=is:issue+is:open) when you hit one in your PR.

Learning with CI infra here, the node-role tag shows different from reported by get nodes, fixing to lower case and trying again:

/test pull-cloud-provider-aws-e2e

**Comment by mtulio** [comment]
This PR is ready for review. I just added minimum changes to improve readiness.

Looks like the failures in the last run was CI infra flake. Checking again in the next round.

Hi @kmala , would you mind taking a look here? Thanks!

**Comment by mtulio** [comment]
Assigning the github recommendations, PTAL?: 
/assign dims nckturner

**Comment by mtulio** [comment]
cc @JoelSpeed @elmiko

File: tests/e2e/loadbalancer.go [hunk 1]
```diff
@@ -41,61 +70,334 @@ var _ = Describe("[cloud-provider-aws-e2e] loadbalancer", func() {
...
+			framework.Logf("namespace for load balancer conig test: %s", ns.Name)
+
+			By("creating a TCP service " + serviceName + " with type=LoadBalancerType in namespace " + ns.Name)
+			lbConfig := newConfigServiceLB()
+			lbConfig.LBJig = e2eservice.NewTestJig(cs, ns.Name, serviceName)
+			lbServiceConfig := lbConfig.buildService(tc.Annotations)
+
+			// Hook: PostConfigService patchs service configuration.
+			if tc.PostConfigService != nil {
+				By("running post run validations")
```
Comment (elmiko) [inline tests/e2e/loadbalancer.go]: i know this is a minor nit, but given that we have the same `By` statement on line 178, should we change this to say "running post configuration on service"?

**Review by elmiko — COMMENTED** [review]
this makes sense to me, i just have a minor nit that might help with triaging.

File: tests/e2e/loadbalancer.go (hunk 1 above)
Comment (mtulio) [reply tests/e2e/loadbalancer.go]: fair point, thanks for cathing that. We also have `By` on line 102, inside `PostConfigService` which would duplicate this one. I'm going to fix it.

**Review by elmiko — COMMENTED** [review]
thanks @mtulio , let's see if this works. feel free to remove the hold once the tests pass.

/approve
/lgtm

/hold for tests

**Comment by mtulio** [comment]
> thanks @mtulio , let's see if this works. feel free to remove the hold once the tests pass.
> 
> /approve /lgtm
> 
> /hold for tests

Thanks! LGTM tests.
/hold cancel
