### PR TITLE
Ensure that addresses are added in network device index order

### LINKED ISSUE #911: DeviceIndex is not respected when processing multiple network interfaces on a node
**What happened**:

In cases where a node has multiple network interfaces, the order in which they are listed from AWS is applied directly to the interfaces list that the CCM produces. Depending on the ordering from AWS, this may or may not be accurate for the node being deployed. Even when `DeviceIndex` is specified, it is not respected.

For example, given this data from AWS:
```json
{
  "Reservations": [
    {
      "Instances": [
        {
          "NetworkInterfaces": [
            {
              "Attachment": {
                "DeviceIndex": 1,
              },
              "MacAddress": "02:0f:d9:6d:bf:eb",
              "PrivateIpAddress": "100.64.2.164",
            },
            {
              "Attachment": {
                "DeviceIndex": 0,
              },
              "MacAddress": "02:5c:60:51:b1:29",
              "PrivateIpAddress": "10.175.4.157",
            }
          ],
        }
      ],
    }
  ]
}
```

The interface with MAC `02:5c:60:51:b1:29` should be the first interface by its `DeviceIndex`, yet it is the second interface due to the ordering from AWS.

**What you expected to happen**:

When `DeviceIndex` is specified, I expect it to be honored when ordering the network interfaces.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a node with multiple network interfaces, and device indexes specified
2. ensure that the ordering from AWS is wrong from device index, or set the device indexes to be wrong based on the MAC address ordering
3. inspect the primary network interface IP on the node object created

**Anything else we need to know?**:

this was solved in the in-tree cloud controller but appears to have not been ported to the out-of-tree controller, see https://github.com/kubernetes/kubernetes/pull/80747

this is the current code in the external ccm, https://github.com/openshift/cloud-provider-aws/blob/release-4.14/pkg/providers/v1/aws.go#L1515

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by javanthropus**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This ensures that the addresses associated with network devices attached to the host are added to a Node resource's address list in order of device index.  For some unknown reason AWS returns the list of network devices for just some of our EC2 instances where the primary device is not first in the list.  Without this code change, the addresses of the secondary devices are listed first in the addresses for a Node, and this breaks the ability to interact with pods on the node, such as fetching logs and creating port forwards, because the apiserver always uses the first address of the Node resource to reach the kubelet but is unable to reach kubelet on any of these other addresses.

**Which issue(s) this PR fixes**:
Fixes #911.

**Special notes for your reviewer**:
None

**Does this PR introduce a user-facing change?**:

```release-note
Addresses associated with the Node resource will be sorted in order of the index of the network device to which they're attached.  In cases where a VPC CNI, such as aws-cni, is used and the order of devices returned for a node is unpredictable, this ensures that Kubernetes uses the right address to interact with the kubelet on the node.
```

### CODE REVIEW

File: pkg/providers/v1/aws.go [hunk 1]
```diff
@@ -1543,6 +1543,11 @@ func extractIPv4NodeAddresses(instance *ec2.Instance) ([]v1.NodeAddress, error)
 
 	addresses := []v1.NodeAddress{}
 
+	// sort by device index so that the first address added to the addresses list is from the first (primary) device
+	sort.Slice(instance.NetworkInterfaces, func(i, j int) bool {
+		return *instance.NetworkInterfaces[i].Attachment.DeviceIndex < *instance.NetworkInterfaces[j].Attachment.DeviceIndex
```
Comment (cartermckinnon) [inline pkg/providers/v1/aws.go:1548]: Can you add checks for a `nil` attachment and use `aws.IntValue` to dereference the index? The EC2 API should return sane values but we shouldn't crash if it doesn't

Comment (javanthropus) [reply pkg/providers/v1/aws.go:1548]: Should I filter out interfaces where the attachment is `nil`, or should I just sort them to the end of the list?  I feel like filtering them out would be the right solution since they should have addresses associated if the interface isn't actually attached to an instance.

Comment (cartermckinnon) [reply pkg/providers/v1/aws.go:1548]: The check here: https://github.com/kubernetes/cloud-provider-aws/pull/909/files/40202804f2189a7e3958261c8a1732bd8fd7686c#diff-97a31d0f193ea0b4e2c538595daf93405351054377458053a5010f6fdb97f4dcR1554-R1556

Should filter those out, so you just need to handle the potential `nil` pointer here. Start or end of the slice doesn't matter to me 😄

Comment (javanthropus) [reply pkg/providers/v1/aws.go]: I believe the updated code should just cause them to be sorted to the end of the list.  It avoids allocating another slice, and the code that pulls the addresses out should ignore them anyway.

**Comment by javanthropus** [comment]
What's the process for back porting changes?  My understanding is that we need to use the 1.27 release branch since our clusters are still running k8s 1.27.

**Comment by cartermckinnon** [comment]
Ah I didn't notice you had this open against `release-1.30`. I changed the base to `master`, and after merge you can open cherrypick PR against older release branches as needed. I use this script to fire them off quickly: https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh

example here: https://kops.sigs.k8s.io/contributing/proposing-a-cherry-pick/

**Comment by javanthropus** [comment]
> Ah I didn't notice you had this open against `release-1.30`. I changed the base to `master` so you'll need to rebase.

Sorry about that.  It wasn't clear what the process is for changes like this.  Should I go ahead and squash my commits when I rebase?

**Comment by cartermckinnon** [comment]
Sure you can go ahead and squash! Thx

**Comment by cartermckinnon** [comment]
/approve

/assign @mmerkes

PTAL

File: pkg/providers/v1/aws.go [hunk 2]
```diff
@@ -928,6 +928,19 @@ func extractIPv4NodeAddresses(instance *ec2.Instance) ([]v1.NodeAddress, error)
 
 	addresses := []v1.NodeAddress{}
 
+	// sort by device index so that the first address added to the addresses list is from the first (primary) device
+	sort.Slice(instance.NetworkInterfaces, func(i, j int) bool {
```
Comment (mmerkes) [inline pkg/providers/v1/aws.go:932]: Can we write a unit test for this to confirm that the ordering is what we intend?

Comment (javanthropus) [reply pkg/providers/v1/aws.go:932]: I could give it a try, but I didn't do so already because I couldn't find much in the way of existing tests here.  As a result, I don't have any good examples to base my work on.  Did I overlook something?

Comment (mmerkes) [reply pkg/providers/v1/aws.go:932]: That's good information to have. I don't know that it necessarily needs to be a strict blocker, but I don't think it would be too crazy.

I don't see any asynchronous calls here, so it should act entirely on the inputs. You could separate this out into another method to really narrow down the testing, but shouldn't be much more scope to leave as is. [Here's a somewhat similar sort of test](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/providers/v1/aws_test.go#L3120-L3177).

Comment (javanthropus) [reply pkg/providers/v1/aws.go:932]: Thanks for the link.  I was looking in the wrong place for tests.  That's not surprising since I'm very green with golang.  I'll try to add some tests tomorrow and push them up.

Comment (javanthropus) [reply pkg/providers/v1/aws.go:932]: I finally managed to understand how the fakes work here, but I don't see any tests for this functionality.  I see some tests for Fargate instances, but they don't use the NetworkInterfaces list and rely solely on the PrivateDnsName and PrivateIpAddress fields of the instance.  Shouldn't that be sufficient for non-Fargate instances as well?  In other words, why does this controller attempt to list all addresses for all network interfaces for a node rather than just the primary address and DNS name?

Comment (javanthropus) [reply pkg/providers/v1/aws.go:932]: @mmerkes, do you know if we can simplify this whole thing and just use the primary address and DNS name of the nodes rather than iterate over all attached addresses?

Comment (javanthropus) [reply pkg/providers/v1/aws.go:932]: A test has been added as requested.

**Comment by javanthropus** [comment]
The last couple of failed test runs don't appear to be related to my change.  @mmerkes or @cartermckinnon, can one of you PTAL?

**Comment by cartermckinnon** [comment]
@javanthropus sorry about that, the CI is busted. If we can't get a fix in shortly I'll override.

**Comment by hakman** [comment]
@javanthropus Please rebase instead of merge. Thanks!

**Comment by cartermckinnon** [comment]
Thanks for fixing this @javanthropus!
