### PR TITLE
Fix route controller create/delete spam: use instanceIDToNodeName in case node name != private DNS

### LINKED ISSUE #318: Instance IDs as node names causes route controller to spam create/delete route
**What happened**:

in kops 1.23 if external CCM is enabled nodes are created with instance ID.
- this breaks listroutes which assumes nodenames are privateDNS https://github.com/kubernetes/cloud-provider-aws/blob/58bc609b9f79e1283b8896011f1590691604b2aa/pkg/providers/v1/aws_routes.go#L70
- this may break checkIfAttachedToNode which also calls mapInstanceToNodeName https://github.com/kubernetes/cloud-provider-aws/blob/58bc609b9f79e1283b8896011f1590691604b2aa/pkg/providers/v1/volumes.go#L110 (need to test)

**What you expected to happen**: instace ids as node names is supproted

**How to reproduce it (as minimally and precisely as possible)**: create 1.23 kops cluster https://github.com/kubernetes/kops/issues/13376
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by wongma7**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: 

The function `mapInstanceToNodeName` assumes that node names are always equal to private dns names. This assumption does not always hold, specifically in 1.23 kops clusters with CCM enabled where  node names are overridden to be instance IDs.

I added `instanceIDToNodeName` as a replacement. It relies on an indexer in the node informer to find nodeName by instance ID. This solution might be heavy-handed, I don't know how expensive exactly it is to have this indexer. If we assume that node names are going to be limited to either private dns or instance ids (or fargate?) then the solution could be simpler: it could check if a node with name equal to instance id exists, as suggested here https://github.com/kubernetes/kops/issues/13376#issuecomment-1069591289, and if not then fall back to assuming that node names are private dns names. Open to suggestions of course...

I tested this in my own cluster, I'll need to work on unit tests. And am considering how we can test this end to end or if such a test is necessary. We only caught this issue in the first place because AWS alerted us that we were making an unusual # of calls.

Test:
1. delete routes with destination 100.96.0.0/24 and 100.96.1.0/24 in VPC console
2. check logging of cloud controller: ~ $ k logs -n kube-system aws-cloud-controller-manager-xnmj5
```
I0317 21:29:45.399248       1 route_controller.go:194] Creating route for node i-001c99c6268df2574 100.96.1.0/24 with hint bd6fb3d1-708e-45ef-8019-01090827d461, throttled 10.433µs
I0317 21:29:45.399295       1 route_controller.go:194] Creating route for node i-001ab2674ef942145 100.96.0.0/24 with hint 24e777a5-cba7-4079-82c6-57d215eb4865, throttled 5.411µs
I0317 21:29:46.129790       1 route_controller.go:214] Created route for node i-001c99c6268df2574 100.96.1.0/24 with hint bd6fb3d1-708e-45ef-8019-01090827d461 after 730.545279ms
I0317 21:29:46.315747       1 route_controller.go:214] Created route for node i-001ab2674ef942145 100.96.0.0/24 with hint 24e777a5-cba7-4079-82c6-57d215eb4865 after 916.451209ms
```
3. check logging of cloud controller 5 mins later, there are no unnecessary Deletes or Creates:  ~ $ k logs -n kube-system aws-cloud-controller-manager-xnmj5

**Which issue(s) this PR fixes**: 
Fixes #318

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix route controller making unnecessary CreateRoute/DeleteRoute AWS API requests in case node names are not private DNS names
```

### CODE REVIEW

File: pkg/providers/v1/aws.go [hunk 1]
```diff
@@ -5028,7 +5044,7 @@ func isFargateNode(nodeName string) bool {
 	return strings.HasPrefix(nodeName, fargateNodeNamePrefix)
 }
 
-func (c *Cloud) nodeNameToProviderID(nodeName types.NodeName) (InstanceID, error) {
+func (c *Cloud) nodeNameToInstanceID(nodeName types.NodeName) (InstanceID, error) {
```
Comment (wongma7) [inline pkg/providers/v1/aws.go:5047]: the provider id / instance id change is not super relevant, will put in separate commit . but I made it cuz strictly speaking all instance ids are provider ids but provider ids are not instance ids (since provider ids should have prefix aws://region or something) so this helped with m y understanding personally ...

Comment (wongma7) [reply pkg/providers/v1/aws.go:5047]: will fix unit tests due to rename as well

**Comment by olemarkus** [comment]
This looks good to me. Like the indexer approach.

File: pkg/providers/v1/aws_routes.go [hunk 2]
```diff
@@ -112,9 +112,13 @@ func (c *Cloud) ListRoutes(ctx context.Context, clusterName string) ([]*cloudpro
 		// Capture instance routes
 		instanceID := aws.StringValue(r.InstanceId)
 		if instanceID != "" {
-			instance, found := instances[instanceID]
+			_, found := instances[instanceID]
```
Comment (nckturner) [inline pkg/providers/v1/aws_routes.go:115]: Do we need this check or can we remove the `instances, err := c.getInstancesByIDs(instanceIDs)` entirely?

File: pkg/providers/v1/aws.go [hunk 3]
```diff
@@ -5051,6 +5071,32 @@ func (c *Cloud) nodeNameToProviderID(nodeName types.NodeName) (InstanceID, error
...
+	if c.nodeInformerHasSynced == nil || !c.nodeInformerHasSynced() {
+		return "", fmt.Errorf("node informer has not synced yet")
+	}
+
+	_, err := c.nodeInformer.Lister().Get(string(instanceID))
+	if err == nil {
+		return types.NodeName(instanceID), nil
+	}
+
+	nodes, err := c.nodeInformer.Informer().GetIndexer().IndexKeys("instanceID", string(instanceID))
```
[the remark this answers is not in the document]
Comment (wongma7) [reply pkg/providers/v1/aws.go:5115]: indexer should work for all cases, the Lister Get is redundant and I was thinking of it as a fast path but in practice I don't think it's any faster than Informer().GetIndexer().IndexKeys, so we an remove.

The Lister  Get would error if the node name is NOT equal to instance ID e.g. if the node name is still set to private dns.

File: pkg/providers/v1/aws_routes.go (hunk 2 above)
Comment (wongma7) [reply pkg/providers/v1/aws_routes.go:115]: I don't know, I didn't think too much of it bc I think it's out of scope of this PR.

But I think the check is wrong  because ListRoutes should return all routes in the cluster's table and let the route controller decide whether it should be deleted. Because right now if there is a zombie route (say a node gets terminated while route controller is down) and then you hit the warning, the zombie will never get cleaned up?

but again I think it's out of scope so I'd rather fix this later

Comment (nckturner) [reply pkg/providers/v1/aws_routes.go:115]: > the zombie will never get cleaned up?

This is what I was wondering about, and I agree I'm pretty sure that check was only there due to necessity and we can remove it now.  The route controller can remove routes if the nodes don't exist: https://github.com/kubernetes/cloud-provider/blob/master/controllers/route/route_controller.go#L236-L257
